// Narrow public API surface for the trimmed chat-only desktop app.

export {
  configureProviderOauth,
  confirmToolAction,
  deleteSession,
  forkSession,
  getCanonicalModelInfo,
  getSession,
  getSessionInsights,
  getSlashCommands,
  getTools,
  listSessions,
  readAllConfig,
  readConfig,
  reply,
  removeConfig,
  resumeAgent,
  searchSessions,
  startAgent,
  startOpenrouterSetup,
  startTetrateSetup,
  status,
  updateFromSession,
  updateSessionName,
  upsertConfig,
} from './sdk.gen';

export type {
  ActionRequired,
  CallToolResponse,
  ConfigKeyQuery,
  ConfigResponse,
  ContentBlock,
  EmbeddedResource,
  Message,
  MessageEvent,
  ModelInfoData,
  Permission,
  Session,
  SessionInsights,
  SystemNotificationContent,
  TokenState,
  ToolConfirmationRequest,
  ToolRequest,
  ToolResponse,
  UpsertConfigQuery,
} from './types.gen';
